#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.4.0'
__CHEETAH_versionTuple__ = (3, 4, 0, 'final', 0)
__CHEETAH_genTime__ = 1739054864.622148
__CHEETAH_genTimestamp__ = 'Sat Feb  8 22:47:44 2025'
__CHEETAH_src__ = 'article.tmpl'
__CHEETAH_srcLastModified__ = 'Sat Feb  8 22:36:53 2025'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class article(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(article, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def header(self, **KWS):



        ## CHEETAH: generated from #block header at line 14, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        if not VFFSL(SL,"noheader",True): # generated from line 15, col 1
            write('''\\usepackage[colorlinks, citecolor=blue, linkcolor=blue, urlcolor=red]{hyperref}
\\urlstyle{same}
\\usepackage{amsmath, amssymb, amsthm}
\\newtheorem{theorem}{Theorem}[section]
\\newtheorem{lemma}[theorem]{Lemma}
\\newtheorem{proposition}[theorem]{Proposition}
\\newtheorem{corollary}[theorem]{Corollary}
\\newtheorem{conjecture}[theorem]{Conjecture}
\\newtheorem{claim}[theorem]{Claim}
\\theoremstyle{definition}
\\newtheorem{definition}[theorem]{Definition}
\\newtheorem{example}[theorem]{Example}
\\newtheorem{remark}[theorem]{Remark}
\\providecommand{\\keywords}[1]{\\textbf{\\textit{Keywords---}} #1}
''')
        write('''
''')
        for macrofile in VFFSL(SL,"macro",True): # generated from line 32, col 1
            write('''\\input{''')
            _v = VFFSL(SL,"macrofile",True) # '$macrofile' on line 33, col 8
            if _v is not None: write(_filter(_v, rawExpr='$macrofile')) # from line 33, col 8.
            write('''}
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''% Generated by <https://github.com/jakub-oprsal/thead> on ''')
        _v = VFFSL(SL,"now",True) # '$now' on line 1, col 59
        if _v is not None: write(_filter(_v, rawExpr='$now')) # from line 1, col 59.
        write('''
%
% ''')
        _v = VFFSL(SL,"title",True) # '$title' on line 3, col 3
        if _v is not None: write(_filter(_v, rawExpr='$title')) # from line 3, col 3.
        write('''
% by ''')
        _v = authors_list(short=True)
        if _v is not None: write(_filter(_v))
        write('''
%
''')
        if VFFSL(SL,"opts",True): # generated from line 6, col 1
            write('''\\documentclass[''')
            _v = ",".join(opts)
            if _v is not None: write(_filter(_v))
            write(''']{''')
            _v = VFFSL(SL,"cname",True) # '$cname' on line 7, col 40
            if _v is not None: write(_filter(_v, rawExpr='$cname')) # from line 7, col 40.
            write('''}
''')
        else: # generated from line 8, col 1
            write('''\\documentclass{''')
            _v = VFFSL(SL,"cname",True) # '$cname' on line 9, col 16
            if _v is not None: write(_filter(_v, rawExpr='$cname')) # from line 9, col 16.
            write('''}
''')
        write('''
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
''')
        self.header(trans=trans)
        write('''
\\title{''')
        _v = VFFSL(SL,"TeXtitle",True) # '$TeXtitle' on line 37, col 8
        if _v is not None: write(_filter(_v, rawExpr='$TeXtitle')) # from line 37, col 8.
        _v = VFFSL(SL,"note",True) # '$note' on line 37, col 17
        if _v is not None: write(_filter(_v, rawExpr='$note')) # from line 37, col 17.
        write('''}

\\author{''')
        _v = VFFSL(SL,"TeXauthors",True) # '$TeXauthors' on line 39, col 9
        if _v is not None: write(_filter(_v, rawExpr='$TeXauthors')) # from line 39, col 9.
        write('''}

\\begin{document}

\\maketitle

''')
        if VFFSL(SL,"abstract",True): # generated from line 45, col 1
            write('''\\begin{abstract}
''')
            _v = VFFSL(SL,"abstract",True) # '$abstract' on line 47, col 1
            if _v is not None: write(_filter(_v, rawExpr='$abstract')) # from line 47, col 1.
            write('''
\\end{abstract}
''')
        write('''
''')
        if VFFSL(SL,"keywords",True): # generated from line 51, col 1
            write('''\\keywords{''')
            _v = ", ".join(VFFSL(SL,"keywords",True))
            if _v is not None: write(_filter(_v))
            write('''}
''')
        write('''
''')
        if VFFSL(SL,"acknowledgements",True) and not VFFSL(SL,"anonymous",True): # generated from line 55, col 1
            write('''\\subsection*{Acknowledgements}

''')
            _v = VFFSL(SL,"self.acknowledgements",True) # '$self.acknowledgements' on line 58, col 1
            if _v is not None: write(_filter(_v, rawExpr='$self.acknowledgements')) # from line 58, col 1.
            write('''

''')
        for file in VFFSL(SL,"content",True): # generated from line 61, col 1
            write('''\\input{''')
            _v = VFFSL(SL,"file",True) # '$file' on line 62, col 8
            if _v is not None: write(_filter(_v, rawExpr='$file')) # from line 62, col 8.
            write('''}
''')
        write('''
''')
        if VFFSL(SL,"appendix",True): # generated from line 65, col 1
            write('''\\appendix
''')
            for file in VFFSL(SL,"appendix",True): # generated from line 67, col 1
                write('''\\input{''')
                _v = VFFSL(SL,"file",True) # '$file' on line 68, col 8
                if _v is not None: write(_filter(_v, rawExpr='$file')) # from line 68, col 8.
                write('''}
''')
        write('''
''')
        if VFFSL(SL,"bib",True): # generated from line 72, col 1
            write('''\\bibliographystyle{''')
            _v = VFFSL(SL,"bibstyle",True) # '$bibstyle' on line 73, col 20
            if _v is not None: write(_filter(_v, rawExpr='$bibstyle')) # from line 73, col 20.
            write('''}
\\bibliography{''')
            _v = ",".join(VFFSL(SL,"bib",True))
            if _v is not None: write(_filter(_v))
            write('''}
''')
        else: # generated from line 75, col 1
            write('''% no bibliography data
''')
        write('''
\\end{document}
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_article = 'respond'

## END CLASS DEFINITION

if not hasattr(article, '_initCheetahAttributes'):
    templateAPIClass = getattr(article,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(article)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=article()).run()


